# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 721399a60cfe1101b34280dd7eb0e17178157a08668d36734a861e3d7dfd34dc231bdf8a4586f87c1a0b4bf024175a29349762f12ab8739b140acce56489c66f

test:
  secret_key_base: e9374e21828f64400f7f75d6a1834482bdcf610c9f5bc0fcae7e6c3847cd060cdd5e2794d088506e773718d622f1d0e5d3104209e5d58b4d1143c1109a0921ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
